version: '2.1'
services:

######################################################
# DATABASE SERVICE
######################################################
  postgres:
      image: postgres:9.6
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - ./mnt/postgres/postgres-data2:/var/lib/postgresql/data
          # copy the sql script to create tables
          #- ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  

######################################################
# AIRFLOW
######################################################

  airflow:
    build: ./docker/airflow
    #image: sundargopal/yararepo1:airflow
    restart: always
    container_name: airflow
    entrypoint: ./scripts/start-airflow.sh
    env_file:
      - .env1
    volumes:
      - ./mnt/airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./mnt/airflow/airflow.cfg:/opt/airflow/airflow.cfg
    # env_file:
    #   - .env
    ports:
      - 8080:8080
  


